//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rosy_bookstore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Rozy_bookshopEntities2 : DbContext
    {
        public Rozy_bookshopEntities2()
            : base("name=Rozy_bookshopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_details { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_image> product_images { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
